name: Daily Devotional

on:
  schedule:
    - cron: "0 15 * * *"   # 每天 UTC 15:00 运行（湾区清晨时段）
  workflow_dispatch:        # 允许手动触发

permissions:
  contents: write           # 允许工作流向仓库写入内容（commit）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate devotional
        run: |
          pip install python-dateutil
          python scripts/generate_devotional.py

      - name: Commit devotional
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "chore: add daily devotional $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit."
          fi
